name: 🏗️  Build
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
      - 'fl[0-9]+.[0-9]+.[0-9]+*'
      - 'fx[0-9]+.[0-9]+.[0-9]+*'
    branches:
      - 'releng'

jobs:
  test_suite:
    name: Run test suite
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        base_image: ['raspios_lite:2021-05-07', 'dietpi:rpi_armv6_buster']

    steps:
      - name: Checkout pynab
        uses: actions/checkout@v2

      - name: Run test suite in chroot environment
        uses: f-laurens/arm-runner-action@v1
        id: arm_runner_tests
        with:
          image_additional_mb: 4096
          base_image: ${{ matrix.base_image }}
          cpu: 'arm1176'
          copy_repository_path: /home/pi/pynab
          optimize_image: no
          commands: |
            sudo useradd pi || true
            sudo sh -c "[ ! -f /etc/sudoers.d/010_pi-nopasswd ] && usermod -aG sudo pi && echo 'pi ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/010_pi-nopasswd || true"
            sudo chown -hR pi:pi /home/pi/pynab
            sudo apt-get update -y
            sudo apt-get install --no-install-recommends -y postgresql libpq-dev git python3 python3-venv python3-dev gettext nginx openssl libssl-dev libffi-dev libmpg123-dev libasound2-dev libatlas-base-dev libgfortran3 libopenblas-dev liblapack-dev zram-tools
            sudo mkdir -p /run/systemd/timesync/ && sudo touch /run/systemd/timesync/synchronized
            sudo apt-get install --no-install-recommends -y alsa-utils xz-utils avahi-daemon
            sudo -u pi taskset -c 0 /bin/bash install.sh ci-chroot-test

  create_image:
    name: Build image
    runs-on: ubuntu-latest
    needs: test_suite
    strategy:
      fail-fast: false
      matrix:
        base_image: ['raspios_lite:2021-05-07', 'dietpi:rpi_armv6_buster']
    if: github.ref == 'refs/heads/releng' || startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout pynab
        uses: actions/checkout@v2

      - name: Define the image name
        id: image_and_branch_name
        run: |
          if [[ "${{ matrix.base_image }}" =~ "raspios" ]]; then
            os_suffix="-raspios"
          elif [[ "${{ matrix.base_image }}" =~ "dietpi" ]]; then
            os_suffix="-dietpi"
          else
            os_suffix=""
          fi
          if [ ${GITHUB_REF/refs\/tags\//} != ${GITHUB_REF} ]; then
            echo ::set-output name=LOCAL_BRANCH::${GITHUB_REF/refs\/tags\//}
            echo ::set-output name=RELEASE_NAME::${GITHUB_REF/refs\/tags\//}
            echo ::set-output name=IMAGE_NAME_SUFFIX::${GITHUB_REF/refs\/tags\//}${os_suffix}
          elif [ ${GITHUB_REF/refs\/heads\//} = "releng" ]; then
            echo ::set-output name=LOCAL_BRANCH::releng
            echo ::set-output name=RELEASE_NAME::releng
            echo ::set-output name=IMAGE_NAME_SUFFIX::releng${os_suffix}
          else
            echo ::set-output name=LOCAL_BRANCH::${GITHUB_REF/refs\/heads\//}
          fi

      - name: Create a release image in chroot environment
        uses: f-laurens/arm-runner-action@v1
        id: arm_runner_install
        with:
          image_additional_mb: 4096
          base_image: ${{ matrix.base_image }}
          cpu: 'arm1176'
          optimize_image: yes
          commands: |
            echo GITHUB_BRANCH=${{ steps.image_and_branch_name.outputs.LOCAL_BRANCH }}
            echo GITHUB_REPOSITORY=${{ github.repository }}
            sudo GITHUB_BRANCH=${{ steps.image_and_branch_name.outputs.LOCAL_BRANCH }} GITHUB_REPOSITORY=${{ github.repository }} /bin/bash setup ci-chroot
            cd / ; sudo rm -rf /pynab
            sudo apt-get autoremove --purge -y
            sudo apt-get clean

      - name: Compress the release image
        run: |
          mv ${{ steps.arm_runner_install.outputs.image }} pynab-${{ steps.image_and_branch_name.outputs.IMAGE_NAME_SUFFIX }}.img
          sudo xz -T 0 -v pynab-${{ steps.image_and_branch_name.outputs.IMAGE_NAME_SUFFIX }}.img

      - name: Upload the image artifact
        uses: actions/upload-artifact@v2
        with:
          name: release_images
          path: pynab-${{ steps.image_and_branch_name.outputs.IMAGE_NAME_SUFFIX }}.img.xz
          if-no-files-found: error
          retention-days: 1

  create_release:
    name: Release
    runs-on: ubuntu-latest
    needs: create_image
    if: github.ref == 'refs/heads/releng' || startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Define the release name
        id: release_name
        run: |
          if [ ${GITHUB_REF/refs\/tags\//} != ${GITHUB_REF} ]; then
             echo ::set-output name=RELEASE_NAME::${GITHUB_REF/refs\/tags\//}
          elif [ ${GITHUB_REF/refs\/heads\//} = "releng" ]; then
             echo ::set-output name=RELEASE_NAME::releng
           else
             echo ::set-output name=RELEASE_NAME::${GITHUB_REF/refs\/heads\//}
          fi

      - name: Download the image artifact(s)
        uses: actions/download-artifact@v2
        with:
          name: release_images

      - name: Create release with releng image
        if: github.ref == 'refs/heads/releng'
        uses: "marvinpinto/action-automatic-releases@v1.1.2"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          draft: true
          title: "Prerelease"
          files: pynab-${{ steps.release_name.outputs.RELEASE_NAME }}*.img.xz

      - name: Create release with release image
        if: startsWith(github.ref, 'refs/tags/')
        uses: "marvinpinto/action-automatic-releases@v1.1.2"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.release_name.outputs.RELEASE_NAME }}
          prerelease: false
          draft: true
          title: ${{ steps.release_name.outputs.RELEASE_NAME }}
          files: pynab-${{ steps.release_name.outputs.RELEASE_NAME }}*.img.xz
