name: 🃏 Sand box
on: workflow_dispatch

jobs:

  clean_nightly_releases:
    name: Clean old nightly releases
    runs-on: ubuntu-latest

    steps:
      - name: Checkout pynab with tags
        uses: actions/checkout@v2
        with:
          # repository hosting the nigthly build
          repository: ${{ github.repository }}
          # all history for tags
          fetch-depth: 0

      - name: Clean old nightly releases
        shell: bash
        run: |
          keep=2
          nightly_pattern=nightly
          origin=origin
          old_tags=$(git tag -l | grep "^${nightly_pattern}" | sort -r | sed "1,${keep}d" | tr '\n' ' ')
          old_builds=$(hub release --include-drafts | grep "^${nightly_pattern}" | sort -r | sed "1,${keep}d" | tr '\n' ' ')
          echo "Old tags to delete:   ${old_tags}"
          echo "Old builds to delete: ${old_builds}"
          echo ${old_builds} | xargs --no-run-if-empty -t -n1 hub release delete
          echo ${old_tags} | xargs --no-run-if-empty -t git push --delete ${origin}

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
